package dev.securemesh.commander.core.security

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import java.nio.charset.StandardCharsets
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Small authenticated-encryption vault for sensitive application fields.
 *
 * Key material is generated inside Android Keystore and is non-exportable. Every value uses a fresh
 * GCM IV generated by the platform Cipher implementation. AAD binds ciphertext to its semantic owner
 * (for example a specific contact/node or message key), so moving ciphertext between records fails
 * authentication instead of silently decrypting to the wrong record.
 */
interface SensitiveDataProtector {
    fun isEncrypted(value: String): Boolean
    fun encryptString(plainText: String, aad: String): String
    fun decryptString(value: String, aad: String): String
}

class SensitiveDataCipher(
    private val keyAlias: String = "securemesh.local.vault.v1",
) : SensitiveDataProtector {
    companion object {
        private const val ANDROID_KEYSTORE = "AndroidKeyStore"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val PREFIX = "smv1:"
        private const val TAG_BITS = 128
    }

    override fun isEncrypted(value: String): Boolean = value.startsWith(PREFIX)

    override fun encryptString(plainText: String, aad: String): String {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, getOrCreateKey())
        cipher.updateAAD(aad.toByteArray(StandardCharsets.UTF_8))
        val cipherText = cipher.doFinal(plainText.toByteArray(StandardCharsets.UTF_8))
        val iv = Base64.encodeToString(cipher.iv, Base64.NO_WRAP)
        val payload = Base64.encodeToString(cipherText, Base64.NO_WRAP)
        cipherText.fill(0)
        return "$PREFIX$iv:$payload"
    }

    /** Returns legacy plaintext unchanged so old installs can be hardened lazily without data loss. */
    override fun decryptString(value: String, aad: String): String {
        if (!isEncrypted(value)) return value
        val body = value.removePrefix(PREFIX)
        val split = body.indexOf(':')
        require(split > 0 && split < body.lastIndex) { "Malformed SecureMesh vault envelope" }
        val iv = Base64.decode(body.substring(0, split), Base64.NO_WRAP)
        val cipherText = Base64.decode(body.substring(split + 1), Base64.NO_WRAP)
        return try {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.DECRYPT_MODE, getOrCreateKey(), GCMParameterSpec(TAG_BITS, iv))
            cipher.updateAAD(aad.toByteArray(StandardCharsets.UTF_8))
            val plain = cipher.doFinal(cipherText)
            try {
                String(plain, StandardCharsets.UTF_8)
            } finally {
                plain.fill(0)
            }
        } finally {
            iv.fill(0)
            cipherText.fill(0)
        }
    }

    private fun getOrCreateKey(): SecretKey {
        val store = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        (store.getKey(keyAlias, null) as? SecretKey)?.let { return it }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        generator.init(
            KeyGenParameterSpec.Builder(
                keyAlias,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setKeySize(256)
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setRandomizedEncryptionRequired(true)
                .build()
        )
        return generator.generateKey()
    }
}
