package dev.securemesh.commander.feature.messages

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import dev.securemesh.commander.core.ui.*
import dev.securemesh.commander.domain.model.*

@Composable fun MessagesScreen(viewModel:MessagesViewModel){val s by viewModel.uiState.collectAsStateWithLifecycle();val error by viewModel.error.collectAsStateWithLifecycle();if(!s.canView)return EmptyState("Messages unavailable","VIEW_MESSAGES was not granted.");val remotes=s.nodes.filter{it.id!=s.localNodeId};var target by remember(remotes){mutableStateOf(remotes.firstOrNull()?.id.orEmpty())};var text by remember{mutableStateOf("")};var selected by remember{mutableStateOf<MeshMessage?>(null)};LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(14.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Text("MESSAGES",style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Black);Text("Hop ACK progress is distinct from end-to-end delivery.",color=SecureMeshColors.Muted)};item{LazyRow(horizontalArrangement=Arrangement.spacedBy(8.dp)){items(remotes,key={it.id}){n->FilterChip(target==n.id,{target=n.id},{Text(n.name)})}}};item{TechnicalCard("Direct conversation"){NodeSelector(target,remotes){target=it};OutlinedTextField(text,{text=it},label={Text("Message")},modifier=Modifier.fillMaxWidth());Button({viewModel.send(target,text);text=""},enabled=s.canSend&&target.isNotBlank()&&text.isNotBlank()){Text("SEND")};if(!s.canSend)Text("SEND_MESSAGE not granted",color=SecureMeshColors.Warning);error?.let{Text(it,color=SecureMeshColors.Critical)}}};val conversation=s.messages.filter{it.destination==target||it.origin==target};if(conversation.isEmpty())item{EmptyState("No messages","No authorized messages in this direct conversation.")}else items(conversation,key={it.id}){m->MessageCard(m){selected=m}}};selected?.let{m->item{MessageDetails(m){selected=null}}}}
@Composable private fun NodeSelector(selected:String,nodes:List<MeshNode>,set:(String)->Unit){var open by remember{mutableStateOf(false)};Box{OutlinedButton({open=true},Modifier.fillMaxWidth()){Text("Destination: ${nodes.firstOrNull{it.id==selected}?.name?:"Select"}")};DropdownMenu(open,{open=false}){nodes.forEach{n->DropdownMenuItem({Text("${n.name} · ${n.id}")},{set(n.id);open=false})}}}}
@Composable private fun MessageCard(m:MeshMessage,open:()->Unit){val color=when(m.finalState){MessageFinalState.DELIVERED->SecureMeshColors.Healthy;MessageFinalState.FAILED,MessageFinalState.EXPIRED->SecureMeshColors.Critical;MessageFinalState.UNKNOWN->SecureMeshColors.Warning;else->SecureMeshColors.Cyan};TechnicalCard("${m.origin} → ${m.destination}"){Text(m.payload);Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){StatusChip(m.progressState.name,color);Text("Final: ${m.finalState}",color=SecureMeshColors.Muted)};if(m.hopTrace.isNotEmpty())Text("Observed ${m.observedRoute().joinToString(" → ")}",color=SecureMeshColors.Muted);TextButton(onClick=open){Text("DETAILS")}}}
@Composable private fun MessageDetails(m:MeshMessage,close:()->Unit){TechnicalCard("MESSAGE ${m.id}"){Metric("Origin",m.origin);Metric("Destination",m.destination);Metric("Progress",m.progressState.name);Metric("Final state",m.finalState.name);Text("Hop trace",fontWeight=FontWeight.Bold);if(m.hopTrace.isEmpty())Text("UNAVAILABLE",color=SecureMeshColors.Muted)else m.hopTrace.forEach{h->Text("${h.from} → ${h.to} · ${h.ackState} · retries ${h.retries?:"UNKNOWN"} · RSSI ${dbm(h.rssi)} · SNR ${snr(h.snr)}",style=MaterialTheme.typography.bodySmall)};Text("Delivery time ${m.deliveryTimeMs()?.let{"${it}ms"}?:"UNKNOWN"}",color=SecureMeshColors.Muted);TextButton(onClick=close){Text("CLOSE")}}}
